Document: maefat
Title: Debian maefat Manual
Author: <insert document author here>
Abstract: This manual describes what maefat is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/maefat/maefat.sgml.gz

Format: postscript
Files: /usr/share/doc/maefat/maefat.ps.gz

Format: text
Files: /usr/share/doc/maefat/maefat.text.gz

Format: HTML
Index: /usr/share/doc/maefat/html/index.html
Files: /usr/share/doc/maefat/html/*.html

  
